name: drum-prediction-environment
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - pip:
      - matplotlib==3.7.0
      - pandas==1.5.3
      - librosa==0.10.0
      - sklearn==0.0
      - numpy==1.23.5
      - tensorflow==2.10.0
      - IPython==8.10.0