name: drum-prediction-environment
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - pip:
      - matplotlib=3.7.1
      - pandas=2.0.2
      - librosa=0.10.0
      - sklearn=0.0
      - numpy=1.24.3
      - tensorflow=2.12.0
      - IPython=8.14.0